language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2'

script: './mvnw clean package'

notifications:
  email:
    recipients:
      - 'nkw8620@gmail.com'

before_install:
  - chmod +x mvnw